### ISSUE TITLE
Load tensorrt api getInferLibVersion failed

### ISSUE THREAD

**Issue by Feng1909** [Irvingao/paddle-inference-ros#1]
您好，请问若要使用TensorRT只需要将`config.enable_tensorrt_engine`取消注释即可吗，我使用Ubuntu18.04, paddle版本为`paddlepaddle_gpu-2.1.2-cp36-cp36m-linux_x86_64.whl`, 使用CUDA10.2, cudnn8.1.0, tensorRT7.1.3.4, 未更改除了enable_tensorrt_engine外的其他代码，发生如下报错：
```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/home/feng1909/paddle/src/paddle_inference_ros/scripts/pp_infer.py", line 157, in <module>
    predictor = predict_config(model_file, params_file)
  File "/home/feng1909/paddle/src/paddle_inference_ros/scripts/pp_infer.py", line 67, in predict_config
    predictor = create_predictor(config)
RuntimeError: (Unavailable) Load tensorrt api getInferLibVersion failed
  [Hint: p_getInferLibVersion should not be null.] (at /paddle/paddle/fluid/platform/dynload/tensorrt.h:114)
```

**Comment by Irvingao** [comment]
@Feng1909 您好，能否将完整的报错信息发给我？请问您使用的硬件平台是什么？
我对于tensorRT问题的几点解释：
1.在使用tensorRT前首先需要确保Paddle inference在GPU下能够正常工作；
2.在使用tensorRT前需要确保您正确安装了tensorRT；
3.在使用tensorRT时需要确保您的模型或算子被paddle-tensorRT所支持，具体支持模型和算子请参考官网：https://paddle-inference.readthedocs.io/en/master/optimize/paddle_trt.html。

**Comment by Feng1909** [comment]
您好，我卸载重装了一次TensorRT后成功运行，效果非常理想，谢谢您
